# Generated by Django 4.0.2 on 2023-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=64)),
                ('partner_logo', models.ImageField(upload_to='partners')),
            ],
        ),
    ]
