# Generated by Django 4.0.2 on 2022-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuurency_name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=10)),
                ('cuurent_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
