# Generated by Django 4.0.2 on 2022-11-11 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet_App', '0002_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='identity',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='identity_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwallet',
            name='identity_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
