# Generated by Django 4.0.2 on 2022-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet_App', '0004_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='identity',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
