# Generated by Django 4.0.2 on 2022-11-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet_App', '0005_currency_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='identity',
            new_name='symbol',
        ),
    ]
