# Generated by Django 4.0.2 on 2023-07-25 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Message_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 25, 19, 7, 35, 704639, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
