# Generated by Django 4.0.2 on 2022-11-14 16:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category title...')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_title', models.CharField(max_length=264, verbose_name='Port Title')),
                ('slug', models.SlugField(max_length=528, unique=True)),
                ('expert', models.CharField(max_length=264, verbose_name='Your expertness')),
                ('skills', models.CharField(max_length=264, verbose_name='Skills')),
                ('keywords', models.CharField(max_length=264, verbose_name='Keywords')),
                ('port_description', ckeditor.fields.RichTextField(verbose_name='Write about you here...')),
                ('port_image', models.ImageField(upload_to='port_images', verbose_name='Image')),
                ('active', models.BooleanField(blank=True)),
                ('rate_amount', models.PositiveIntegerField(verbose_name='Hourly rate')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('port_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_author', to=settings.AUTH_USER_MODEL)),
                ('port_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_category', to='Main_App.category')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_given_ratings', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=264, verbose_name='Post Title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('required_skills', models.CharField(max_length=50, verbose_name='Required Skill')),
                ('keywords', models.CharField(max_length=264, verbose_name='Keywords')),
                ('post_description', ckeditor.fields.RichTextField(verbose_name='Write your job description here...')),
                ('deadline', models.DateField()),
                ('post_image', models.ImageField(upload_to='post_images', verbose_name='Image')),
                ('active', models.BooleanField(blank=True)),
                ('budget_amount', models.PositiveIntegerField(verbose_name='Budget amount..')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_post', to='Main_App.category')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PortImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='port_images/')),
                ('port', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='port_bulk_images', to='Main_App.port')),
            ],
            options={
                'verbose_name': 'portimagegallery',
                'verbose_name_plural': 'port image gallery',
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_message', models.TextField(verbose_name='Write about your work...')),
                ('hire_amount', models.IntegerField(verbose_name='Budget amount...')),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_hire', to='Main_App.port')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_hire', to='Main_App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_note', models.TextField(verbose_name='Send note...')),
                ('bid_amount', models.IntegerField(verbose_name='Bid amount...')),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_bid', to='Main_App.port')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bid', to='Main_App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bid_date'],
            },
        ),
    ]
