# Generated by Django 4.0.2 on 2022-11-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Categories'},
        ),
    ]
