# Generated by Django 4.0.2 on 2022-11-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateField(verbose_name='Deadline...'),
        ),
    ]
