# Generated by Django 4.0.2 on 2022-11-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_App', '0003_alter_post_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_App.port')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
