# Generated by Django 4.0.2 on 2023-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0004_savedport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='rate_amount',
            field=models.PositiveIntegerField(verbose_name='Order rate'),
        ),
    ]
