# Generated by Django 4.0.2 on 2023-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0005_alter_port_rate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
