# Generated by Django 4.0.2 on 2023-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0006_port_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('bidded', 'Bidded'), ('canceled', 'Canceled'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted')], default='bidded', max_length=10),
        ),
    ]
