# Generated by Django 4.2.8 on 2023-12-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0007_bid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('email', models.CharField(max_length=64, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('title', models.CharField(max_length=164, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('files', models.FileField(blank=True, null=True, upload_to='work_files', verbose_name='Attachment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_public_post', to='Main_App.category')),
            ],
        ),
    ]
