# Generated by Django 4.0.2 on 2022-11-18 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0002_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='verification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
