# Generated by Django 4.0.2 on 2023-06-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0003_alter_verification_options_verification_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=200),
        ),
    ]
