# Generated by Django 4.0.2 on 2022-10-23 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('amount', models.IntegerField(verbose_name='Offer ammount ')),
                ('expected_time', models.DateField(verbose_name='Expected submission date...')),
                ('accepted', models.BooleanField(default=False)),
                ('support', models.IntegerField(verbose_name='How many times support will give?')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_offer', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_offer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(verbose_name='Instructions...')),
                ('amount', models.FloatField(default=0)),
                ('deadline', models.DateTimeField(verbose_name='Last date of submission...')),
                ('payment_confirm', models.BooleanField(default=False)),
                ('payment_success', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_order', to=settings.AUTH_USER_MODEL)),
                ('offer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_offer', to='Work_App.offer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RunningWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name="Yes I'm ready to start this work.")),
                ('work_track', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_running_work', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_running_work', to=settings.AUTH_USER_MODEL)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='running_work', to='Work_App.order')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RunningWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_files', verbose_name='Work File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_files', to='Work_App.runningwork')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_confirmation', models.BooleanField(default=False)),
                ('customer_confirmation', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_complete_order', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_complete_order', to=settings.AUTH_USER_MODEL)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complete_order', to='Work_App.order')),
                ('work_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complete_work', to='Work_App.runningwork')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
