# Generated by Django 4.0.2 on 2022-11-11 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningworkfiles',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
