# Generated by Django 4.0.2 on 2022-11-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0002_runningworkfiles_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningworkfiles',
            old_name='created_time',
            new_name='date_created',
        ),
    ]
