# Generated by Django 4.0.2 on 2022-11-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0003_rename_created_time_runningworkfiles_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningworkfiles',
            name='file_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
