# Generated by Django 4.0.2 on 2022-11-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0004_runningworkfiles_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningworkfiles',
            options={'ordering': ['-date_created']},
        ),
    ]
