# Generated by Django 4.0.2 on 2022-11-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0005_alter_runningworkfiles_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='accepted',
            new_name='canceled',
        ),
    ]
