# Generated by Django 4.0.2 on 2022-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0007_order_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningwork',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
