# Generated by Django 4.0.2 on 2022-11-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0009_report_delete_ratings_alter_completework_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
