# Generated by Django 4.0.2 on 2023-06-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0010_offer_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirm',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_success',
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Checkout', 'Checkout'), ('Pending', 'Pending'), ('Succeed', 'Succeed')], default='Checkout', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Running', 'Running'), ('Completed', 'Completed')], default='Placed', max_length=10),
        ),
    ]
