# Generated by Django 4.0.2 on 2023-06-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_App', '0011_remove_offer_accepted_remove_offer_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Placed', 'Placed'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Running', 'Running'), ('Completed', 'Completed')], default='Created', max_length=10),
        ),
    ]
