# Generated by Django 4.0.2 on 2023-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='browser',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
